spring:
  application:
    name: systemcalls

  security:
      oauth2:
        client:
          registration:
            github:
              clientId: $OAUTH2_CLIENT_ID
              clientSecret: $OAUTH2_CLIENT_SECRET